### ISSUE TITLE
What is the intended way to use an ir.Param?

### ISSUE THREAD

**Issue by pwaller** [mewmew/l#1]
`types.FuncType` seems to have `Params []types.Type`, but `ir.Param` does not implement `Equal`. Is this an oversight, or is it intended to instead use a basic type and call `SetName` on it?

**Comment by pwaller** [comment]
I have a branch which adds the `Equal` method. It compiles, but I can't test whether it is doing what I expect because I ran into #2, so I am stuck for the moment.

**Comment by pwaller** [comment]
Still unsure on this one until I make a bit more progress, but the answer is likely to be `LocalDef` or similar, as in #2. I'll come back if I have further issues.

**Comment by mewmew** [comment]
Glad to see you excited about this @pwaller. It is indeed possible (although not yet easy) to use the `ir` package of mewmew/l to create functions with parameters, and invoke those functions from other functions.

Note, this is still early days for the `mewmew/l` repo. As you may have noticed, the API of llir/llvm is far more pleasant to use. The intention is to merge the feature complete assembly parser of mewmew/l into the API pleasant llir/llvm repo within the following months. The exact details of this merge will be worked out then and I'd be happy to read out to you, if you'd like to beta test the new release before marking it with `v0.3.0` :)

Below follows an example (https://play.golang.org/p/U-B9Lm5GAUp) which outputs the following LLVM IR.

```llvm
define i32 @foo(i32 %a, i32 %b) {
	%result = add i32 %a, %b
	ret i32 %result
}
define i32 @main() {
	%result = call i32 @foo(i32 12, i32 30)
	ret i32 %result
}
```

```go
package main

import (
	"fmt"
	"math/big"

	"github.com/mewmew/l/ir"
	"github.com/mewmew/l/ir/constant"
	"github.com/mewmew/l/ir/types"
)

func main() {
	// Module.
	m := &ir.Module{}

	// foo function.
	aParam := &ir.Param{
		Typ:  types.I32,
		Name: "a",
	}
	bParam := &ir.Param{
		Typ:  types.I32,
		Name: "b",
	}
	params := []*ir.Param{
		aParam,
		bParam,
	}
	fooSig := &types.FuncType{
		Name:    "foo",
		RetType: types.I32,
		Params:  []types.Type{types.I32, types.I32},
	}
	fooResult := &ir.LocalDef{
		Name: "result",
		Inst: &ir.InstAdd{
			X: aParam,
			Y: bParam,
		},
	}
	fooEntry := &ir.BasicBlock{
		Insts: []ir.Instruction{
			fooResult,
		},
		Term: &ir.TermRet{
			X: fooResult,
		},
	}
	fooBlocks := []*ir.BasicBlock{
		fooEntry,
	}
	foo := &ir.Function{
		RetType: types.I32,
		Name:    "foo",
		Params:  params,
		Blocks:  fooBlocks,
		Sig:     fooSig,
		Typ:     types.NewPointer(fooSig),
	}
	m.Funcs = append(m.Funcs, foo)

	// main function.
	mainSig := &types.FuncType{
		Name:    "main",
		RetType: types.Void,
	}
	args := []ir.Argument{
		&ir.Arg{
			X: &constant.Int{
				Typ: types.I32,
				X:   big.NewInt(12),
			},
		},
		&ir.Arg{
			X: &constant.Int{
				Typ: types.I32,
				X:   big.NewInt(30),
			},
		},
	}
	mainResult := &ir.LocalDef{
		Name: "result",
		Inst: &ir.InstCall{
			RetType: types.I32,
			Callee:  foo,
			Args:    args,
		},
	}
	mainEntry := &ir.BasicBlock{
		Insts: []ir.Instruction{
			mainResult,
		},
		Term: &ir.TermRet{
			X: mainResult,
		},
	}
	main := &ir.Function{
		RetType: types.I32,
		Name:    "main",
		Blocks: []*ir.BasicBlock{
			mainEntry,
		},
		Sig: mainSig,
		Typ: types.NewPointer(mainSig),
	}
	m.Funcs = append(m.Funcs, main)

	// Print LLVM IR assembly of module.
	fmt.Println(m)
}
```

**Comment by pwaller** [comment]
Thanks for that; I did get it working, I was just confused in this case - mistakenly trying to use a Param in a FuncType rather than a Function. I think I had just not yet found the `Function.Params` field.

I would be happy to beta test and continue to try and poke holes. I'd like to start using the new thing and try and reach some kind of stability as soon as reasonable :). Feel free to contact me via the email in my profile or in Gophers slack.

**Comment by mewmew** [comment]
> I would be happy to beta test and continue to try and poke holes. I'd like to start using the new thing and try and reach some kind of stability as soon as reasonable :). Feel free to contact me via the email in my profile or in Gophers slack.

Great! I'll do that. Still out on vacation, so will have more focused time working on this towards the end of August :) I'll ping you as soon as there is something interesting to play with.
