### ISSUE TITLE
Most Inst* types don't satisfy the Instruction interface?

### ISSUE THREAD

**Issue by pwaller** [mewmew/l#2]
Most `Inst*` types (e.g, `InstAdd`) don't satisfy the instruction interface; here are the few that do:

https://github.com/mewmew/l/blob/935e562f92c3ad2bd406e7c262c0497afaddcce8/ir/sumtypes.go#L116-L120

And therefore won't fit into the `(*BasicBlock).Insts` field? https://github.com/mewmew/l/blob/935e562f92c3ad2bd406e7c262c0497afaddcce8/ir/basic_block.go#L20-L29

Am I missing something? How far off is this from being able to be used? I'd like to help, if I can with a reasonably small time investment.

I see also that `Insts` can't be used as values, so it's not clear how to build the IR at the moment.

**Comment by pwaller** [comment]
Just found my way to https://godoc.org/github.com/mewmew/l/ir#LocalDef, which answers part of the question :)

https://github.com/mewmew/l/blob/935e562f92c3ad2bd406e7c262c0497afaddcce8/ir/instruction.go#L15-L21

**Comment by pwaller** [comment]
This is obviously it.

**Comment by mewmew** [comment]
Hi @pwaller. Glad you found it. Yes, you are right, `LocalDef` is indeed the way to go. The basic idea being that not every instruction is a value. So `LocalDef` is used to distinguish this fact.

Good catch though, I'll add this to the documentation of [value.Value](https://godoc.org/github.com/mewmew/l/ir/value#Value) to make it more clear for future use.
